### ISSUE TITLE
RFC0019 - Logging

### ISSUE THREAD

**Issue by dennisdegouw** [iStandaarden/iWlz-RequestForComment#17]
### Link naar RFC

**link naar [RFC0019 - Logging](https://github.com/iStandaarden/iWlz-RFC/blob/main/RFC/RFC0019%20-%20Logging.md)**

### Onderwerp

Logging. Eventueel i.r.t. NEN7510/7513

### RFC heeft impact op

- [ ] Indicatieregister
- [ ] Bemiddelingsregister - Centraal
- [ ] Bemiddelingsregister - Decentraal
- [ ] CIZ back-office
- [ ] CIZ Netwerkadapter
- [ ] nID
- [ ] Silvester
- [ ] Raadplegers / GraphQL
- [ ] anders, (geef hieronder aan)

### Selecteer in de kolom rechts het project "RFC-netwerkmodel"

- [X] done

**Comment by rvanrest** [comment]
Is opgesplitst in [RFC0021](#38) en [RFC0022](#37)
